org: sessionsimagesorg
app: sessions-lamda
service: sessions-lamda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
      
plugins:
  - serverless-offline
